project:
  type: book
book:
  title: DATA 545 Tutorial
  author: Stacy DeRuiter
  date: 8/20/2025
  chapters:
  - index.qmd
  - part: Getting Started
    chapters:
    - install-r.qmd
    - r-basics.qmd
    - how-to-quarto.qmd
    - r-results.qmd
    - math-notation.qmd
  - part: graphics-design.qmd
    chapters:
    - graph-design-no-junk.qmd
    - graph-design-color.qmd
    - graph-design-text-elements.qmd
    - graph-design-summary.qmd
  - part: graphics-choose.qmd
    chapters:
    - graphics-choose-var-types.qmd
    - graphics-choose-one-cat.qmd
    - graphics-choose-one-quant.qmd
    - graphics-choose-multiple-cat.qmd
    - graphics-choose-multiple-quant.qmd
    - graphics-choose-cat-quant-mix.qmd
  - part: graphics-code.qmd
    chapters:
    - graphics-code-ggformula.qmd
    - graphics-code-data.qmd
    - graphics-code-plots.qmd
  - part: design-intro.qmd
    chapters:
    - design.qmd
    - plan.qmd
  - part: "Multiple Linear Regression"
    chapters:
    - lm-fit.qmd
    - lm-assess.qmd
    - lm-interp.qmd
    - lm-interp-more.qmd
  - part: "Interactions"
    chapters:
    - interactions.qmd
  - part: "Likelihood"
    chapters:
    - mle.qmd
  - part: "Count Regression"
    chapters:
    - count-regression-1.qmd
    - count-regression-2.qmd
  - part: "Binary Regression"
    chapters:
    - binary-regression-1.qmd
    - binary-regression-2.qmd
  - part: "Zero Inflation"
    chapters:
    - zi-od.qmd
  - part: "More Fun Between 0-1"
    chapters:
    - quasibinomial.qmd
    - beta.qmd
  - part: "Hierarchical Models"
    chapters:
    - hier1.qmd
    - hier2.qmd
  - references.qmd
  page-footer:
    center:
    - text: License
      href: cclicense.md
  page-navigation: true
  search: true
  repo-url: https://github.com/stacyderuiter/data545-tutorials/
  repo-actions: [issue, edit]
  sidebar: 
    collapse-level: 1
number-depth: 2
bibliography: references.bib
format:
  live-html:
    theme: flatly
    css: _include/webex.css
    include-after-body: _include/webex.js
engine: knitr
editor: source
